name: union
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  page_transition: ^2.0.9
  rive: ^0.10.1
  table_calendar: ^3.0.8
  avatar_stack: ^1.1.2
  flutter_slidable: ^2.0.0
  provider: ^6.0.5
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  google_sign_in: ^5.4.3
  firebase_storage: ^11.0.10
  image_picker: ^0.8.6
  flutter_iconpicker: ^3.2.2
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # Image
    - asset/img/
    # Rive
    - asset/rive/

  fonts:
    - family: RobotoMono # English-only-Font
      fonts:
        - asset: asset/font/RobotoMono/RobotoMono-Thin.ttf
          weight: 200
        - asset: asset/font/RobotoMono/RobotoMono-Light.ttf
          weight: 300
        - asset: asset/font/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
    - family: Kodchasan # English-only-Font
      fonts:
        - asset: asset/font/Kodchasan/Kodchasan-Medium.ttf
          weight: 500
    - family: Lato
      fonts:
        - asset: asset/font/Lato/Lato-Thin.ttf
          weight: 100
        - asset: asset/font/Lato/Lato-Light.ttf
          weight: 300
        - asset: asset/font/Lato/Lato-Regular.ttf
          weight: 400
        - asset: asset/font/Lato/Lato-Bold.ttf
          weight: 700
        - asset: asset/font/Lato/Lato-Black.ttf
          weight: 900
